src/views/Generator/NewRuleMenu.tsx
src/views/Generator/TestRuleContainer/TestRuleContainer.tsx

fix: use equal spacing between generator options buttons

---

src/globalStyles.ts

Fixes z-index issue with scrollbars when viewing scrollable request list. 
Before:
After:

fix: Scrollbars covered by request group

---

src/components/WebLogView/Row.tsx
src/utils/harToProxyData.ts
src/utils/staticAssets.ts

This PR fixes 2 issues:
1. Inconsistency of URL path between data from proxy and loaded har file: proxy would return path including query params, while `harToProxyData` returned path only. 
2. The `isNonStaticAssetResponse` not striping query params from path and falsely treating URLs as static assets, for example: test.k6.io/home?foo=bar.js
How to test:
- Use the attached har file to verify the request to `https://test.k6.io/?foo=bar.js` is no longer treated as a static asset.
- Create a generator and verify it's not treated as static assets in Validator either
[2024-09-25_06-32-30.har.zip](https://github.com/user-attachments/files/17126179/2024-09-25_06-32-30.har.zip)

fix: Requests falsely treated as static assets

---

src/components/WebLogView/Details.tsx
src/components/WebLogView/RequestDetails/Payload.tsx
src/components/WebLogView/RequestDetails/utils.ts
src/components/WebLogView/WebLogView.tsx
src/views/Generator/RulePreview/CorrelationPreview.tsx

Resolves https://github.com/grafana/k6-studio/issues/207
- Click a request in correlation rule preview will open inspector
- Sync `selectedRequest` to show changes when editing correlation rule

fix: Inspect requests matched by correlation

---

README.md

Adds the quickstart video in the readme and the troubleshooting section about proxy failing to start on macos.

docs: add quickstart video

---

.eslintrc.json
src/hooks/useOverflowCheck.ts
src/views/Recorder/Recorder.tsx

This PR fixes eslint warnings in the `Recorder.tsx` component as well as the `useOverflowCheck` hook.
- Run `npm run lint`
- Check that no warnings are outputted

fix: eslint warnings in Recorder and useOverflowCheck

---

src/hooks/useAutoScroll.test.ts
src/hooks/useCloseSplashScreen.test.ts
src/hooks/useCreateGenerator.test.ts
src/hooks/useListenProxyData.test.ts
src/hooks/useOverflowCheck.test.ts
src/hooks/useProxyDataGroups.test.ts
src/hooks/useRunChecks.test.ts
src/hooks/useRunLogs.test.ts
src/hooks/useScriptPreview.test.ts
src/hooks/useSetWindowTitle.test.ts
src/hooks/useTheme.test.ts
src/test/factories/generator.ts
src/test/factories/k6Check.ts
src/test/factories/k6Log.ts
src/test/factories/proxyData.ts
src/test/utils/mockMatchMedia.ts

This PR adds missing tests for the React hooks present in `./src/hooks/`
N/A
N/A

test: add missing tests for React hooks

---

src/codegen/codegen.ts
src/codegen/codegen.utils.test.ts
src/codegen/codegen.utils.ts
src/utils/headers.ts

Currently, when exporting a script, the Studio generates checks for all requests in a redirect chain. For example, the URL `http://www.k6.io` does 3 redirects.
```sh
$ curl -v -L http://www.k6.io 2>&1 | grep -i "^< location:"
< Location: https://www.k6.io/
< location: http://k6.io/index.html
< Location: https://k6.io/index.html
```
Right now, one check for each request above is generated when exporting the script, which is unexpected behaviour. 
This PR introduces logic responsible for identifying and resolving a redirect chain, ensuring that only the initial request and the check for the final response are present.
Example: Request to `http://www.k6.io` (first request in the chain) checks for the response in `https://k6.io/index.html` (final response in the chain).
- Create a recording …

feat: merge redirect chains

---

README.md
package-lock.json
package.json
src/components/Layout/ActivityBar/ActivityBar.tsx
src/components/Layout/ActivityBar/ApplicationLogButton.tsx
src/hooks/useCreateGenerator.test.ts
src/hooks/useCreateGenerator.ts
src/index.tsx
src/logger.ts
src/main.ts
src/preload.ts
src/proxy.ts
src/views/Generator/ExportScriptDialog/ExportScriptDialog.tsx
src/views/Generator/Generator.hooks.ts
src/views/Generator/Generator.tsx
src/views/Generator/RecordingSelector.tsx
src/views/Recorder/Recorder.tsx

This PR introduces changes needed to capture caught and uncaught exceptions to a log file. This will enable us to troubleshoot issues more efficiently.
Here's an example of a log file being generated by the Studio. This includes errors raised by the proxy, IpcMain call and unhandle exceptions.
```log
[2024-10-07 12:06:39.823] [error] mitmproxy/certs.py:112: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.
[2024-10-07 12:06:39.824] [error] /Users/username/www/k6-studio/resources/mac/arm64/k6-studio-proxy: Invalid proxy mode specification: regular@AAA (invalid port: AAA)
[2024-10-07 12:08:10.704] [error] Error: Error invoking remote method 'har:open': Error: ENOENT: no such file or directory, open …
```

feat: persist application logs

---

src/main.ts

This PR fixes an issue on Mac OS where the main window would not be re-created from the Dock after being closed.
On Mac OS:
- Start k6 studio
- Close k6 studio window (cmd+w)
- Click on k6 studio in the dock
- Check that the window has been re-created
- Check that chokidar still works as expected (by manually removing or creating files in the k6 Studio Recordings/Scripts directory)
Resolves https://github.com/grafana/k6-studio/issues/231

fix: restore window from dock on mac os

---

src/codegen/codegen.ts
src/codegen/codegen.utils.test.ts
src/codegen/codegen.utils.ts
src/utils/headers.ts

Websocket requests are now removed from the generated script file to avoid issues due to websockets not yet supported
Record a website with websockets, try to validate it and see no issue related to the protocol and the request missing for the `101` switching protocol.
Fix: #241

fix: remove websocket requests from recording

---

src/codegen/codegen.test.ts
src/codegen/codegen.ts
src/rules/correlation.ts
src/rules/correlation.utils.ts
src/rules/customCode.ts
src/rules/parameterization.test.ts
src/rules/parameterization.ts
src/rules/rules.ts
src/rules/shared.ts
src/rules/verification.ts
src/schemas/rules.ts
src/test/fixtures/correlationRecording.ts
src/test/fixtures/parameterizationRules.ts
src/types/rules.ts
src/utils/prettify.ts
src/views/Generator/Generator.utils.ts
src/views/Generator/RulePreview/CorrelationPreview.tsx

This is the first PR of parameterization rule implementation, includes rule logic, unit tests, and a refactor of how we currently apply rules.
Some rules need to have a state to keep track of extracted value, requests matched and sequential variable IDs. Currently, it was done by using `correlationState` object, which was passed as argument when applying rules. Parameterization rule required a state to keep track of replaced requests and, while similar to correlation state, it didn't require all its properties. 
To address this, I've introduced Rule instances with the following structure:
```ts
export interface RuleInstance {
apply: (request: RequestSnippetSchema) => RequestSnippetSchema
rule: TestRule
state: CorrelationState | ParameterizationState | other 
}
```
This allowed to …

feat: Add parameterization rule logic

---

src/main.ts
src/schemas/appSettings.ts
src/settings.ts

This PR persists the window bounds (x, y, width, and height) in the settings file so these options are remembered next time the application restarts.
- launch the app
- resize the window and move it around the screen
- reopen the app
- check that position and dimensions are remembered
Resolves https://github.com/grafana/k6-studio/issues/238

feat: remember window size and position

---

src/settings.ts

fix: settings schema parse

---

src/components/Form/FileUploadInput.tsx
src/components/Form/index.ts
src/components/Settings/RecorderSettings.tsx
src/components/Settings/SettingsDialog.tsx
src/components/Settings/UpstreamProxySettings.tsx
src/main.ts
src/preload.ts
src/proxy.ts
src/schemas/appSettings.ts
src/settings.ts

This PR adds a new field in settings to allow users to input the certificate file (`pem`, `p12` or `cer`) so a trusted connection can be established with the upstream server if it requires SSL.
In your local dev environment, there is a directory in `resources/certificates`. This directory will be used to initialize a new instance of mitmproxy for testing purposes.
Launch a new instance of mitmproxy with SSL configured, pointing the certificate folder to your local environment.
```
$ mitmdump --mode regular@7000 --set confdir=/path/to/k6-studio/resources/certificates
```
Happy path:
- In k6 Studio, go to Settings and set the proxy to be `upstream` and point to the other instance of mitmproxy
- In "Certificate path", select the `mitmproxy-ca-cert.pem` (for macOS) or `mitmproxy-ca-cert.p12` …

fix: failed to establish a connection with the upstream server

---

src/views/Recorder/RequestsSection.tsx

https://github.com/user-attachments/assets/e746b529-b62d-4651-8a9b-9273aae68688
When filtering requests in the recording preview, the no data state is shown if there are no matches. This hides the filter input and makes it impossible to reset the filter without closing the recording and opening it again.
1. Open a recording.
2. Focus the filter input
3. Smash your palm on the keyboard a few times
The filtering should behave the same way as when filtering during recording: the list should just be empty.
ssue(s)

fix: Can't clear filter in recording preview when there are no matches

---

src/components/Settings/SettingsDialog.tsx

fix: Settings dialog doesn't always fit inside app window

---

src/components/Layout/ActivityBar/ActivityBar.tsx
src/components/Layout/ActivityBar/ProxyStatusIndicator.tsx
src/components/Settings/ProxySettings.tsx
src/store/ui/useStudioUIStore.ts

feat: Proxy status indicator

---

src/codegen/codegen.test.ts
src/codegen/codegen.ts
src/codegen/codegen.utils.ts
src/hooks/useScriptPreview.ts
src/rules/correlation.ts
src/test/fixtures/correlationRecording.ts
src/views/Generator/Generator.utils.ts

Fixes a bug where correlation rules wouldn't be applied correctly between groups. Also, I've added grouped recording to the unit test to reproduce the regression. 
[Archive.zip](https://github.com/user-attachments/files/17517390/Archive.zip)
Download attached recording and generator, verify:
- Correlation value is extracted only once
- Correlated value is applied to post body
- Group are added correctly

fix: apply correlation between groups

---

src/main.ts

This PR introduces logic that prevents the proxy from being stuck on an infinite restarting loop. This is known to happen in two occasions:
- When the option to automatically find a port is set to `false` and the currently selected port is busy
- On Windows when there are instances of the proxy still running before new settings can be applied
- Launch an instance of k6 Studio and set the proxy port
- Launch a separate instance of k6 Studio, set the option to automatically find a port to `false` and use the same port as the previous instance.
Resolves https://github.com/grafana/k6-studio/issues/273

fix: prevent infinite error loop on proxy restart

---

src/main.ts
src/menu.ts

This PR removes some properties from the application menu as long as their key bindings, including:
- Reload: `CMD + R`
- Force reload: `CMD + Shift + R`
- Toggle developer tools: `CMD + Option + I`
- change the `NODE_ENV` variable in your localhost and check that `CMD + R` and other shortcuts mentioned above no longer work
- check that the "app menu" is not present on a Windows build
Resolves https://github.com/grafana/k6-studio/issues/274

fix: disable window reloading in prod build

---

src/rules/correlation.ts
src/rules/correlation.utils.ts
src/rules/customCode.ts
src/rules/parameterization.ts
src/rules/utils.ts
src/schemas/rules.ts
src/utils/rules.ts
src/views/Generator/RuleEditor/CorrelationEditor.tsx

- Fixes correlation replacer filter, previously it wasn't applied. 
- Make correlation replacer selector optional, allowing users to filter by request path without having to define custom selector.
- Test correlation without replacer filter
- Test correlation with replacer filter
- Test correlation with custom replacer selector

fix: Replacer filter not applied

---

src/codegen/codegen.test.ts
src/codegen/codegen.ts
src/rules/correlation.ts
src/rules/parameterization.test.ts
src/rules/parameterization.ts
src/rules/rules.ts
src/rules/shared.ts
src/schemas/rules.ts
src/test/fixtures/parameterizationRules.ts
src/types/rules.ts
src/utils/groups.ts

Add logic to support parameterization rule custom code value. The snippet will be wrapped in a function `getCorrelationValueN`. This is different to custom code rule where the snippet is dropped into script without wrapping it, but I went with this approach as it more versatile and helps avoid variable name collision. Also, in the future this could be extended to pass request details to the custom code function to allow more customization, e.g.,: `getCorrelationValue0(params, headers, body)`.
The UI for adding custom code parameterization will be added in a separate PR. 
- Manually add parameterization rule with custom code
- Verify snippet is added to script
- Verify snippet is referenced in request
- Verify snippet function is added only once when referenced in multiple requests

feat: Add parameterization custom code logic

---

src/components/PopoverDialogs.tsx
src/components/WebLogView/Filter.hooks.ts
src/views/Generator/Allowlist/Allowlist.tsx
src/views/Generator/Allowlist/AllowlistDialog.tsx
src/views/Generator/GeneratorSidebar/RequestList.tsx
src/views/Generator/TestOptions/TestOptions.tsx
src/views/Recorder/RequestsSection.tsx

Use popover style dialog for allow list to match the style of test options. It also removes "save" and "discard" buttons from the allow list dialog to match other forms. The changes are reflected immediately without closing dialog. 
- Verify dialog is automatically opened for new recordings
- Verify dialog is opened when switching to recording with additional hosts or different hosts
- Try to add/remove hosts, switch static assets

fix: Unify dialog style between test options and allowed hosts

---

src/views/Generator/RuleEditor/RuleEditor.tsx

Prevent rule editor from closing when hitting enter. 
1. Create or edit an existing rule.
2. Focus an input.
3. Hit enter.
4. Verify rule form is not closed.

fix: don't close rule editor when hitting enter

---

src/rules/shared.ts
src/views/Generator/RulePreview/ParameterizationPreview.tsx

Show replaced path in parameterization preview
Before:
After:

fix: replace url and path for url regex matchers

---

src/components/WebLogView/Row.tsx

Add hover state on request rows to serve as indicator that rows are clickable.

fix: Add requests hover state

---

src/views/Recorder/Recorder.tsx

Previously we would show empty screen while recorder is starting and we haven't received any requests yet. It also didn't allow changing group name after clearing requests. This PR adds "Requests will appear here" loading indicator and fixes group rename issue. 
Before:
https://github.com/user-attachments/assets/7cceaa53-88e7-42b2-9194-334476c1fa96
After:
https://github.com/user-attachments/assets/d62cdcc4-5787-49f7-8a26-9f9a2efffe14
Verify loading state and empty state is displayed as expected in recorder, recorded har viewer and validator.

fix: Show loading indicator while browser is starting when recording

---

src/components/Layout/Layout.tsx
src/main.ts
src/preload.ts
src/views/Generator/Generator.tsx
src/views/Generator/UnsavedChangesDialog.tsx

This PR triggers the dialog to save the generator (if unsaved changes are present) when closing the main window.
- Open the generator
- Make modifications to it
- Close the main window
- Check that the save dialog is triggered
https://github.com/user-attachments/assets/80506356-bacf-4b93-914f-09c6c4435ac2
Resolves https://github.com/grafana/k6-studio/issues/239

feat: prompt to save generator on exit

---

src/views/Generator/Allowlist/Allowlist.tsx

We've recently updated allowlist dialog to be displayed as an inline popover to match test options' dialog style. Although this approach is effective, we would like to direct the user's attention towards the allowlist when the user's input is required. This includes when creating a new generator, opening a generator without a set allowlist, or switching between recordings that contain different hosts. With this change, allowlist could be displayed both as popover or modal depending on this condition:
If allowlist is triggered by indirect action (open generator, switch recording) → show as modal.
If allowlist button is clicked inside generator → show as popover.
Could use some feedback whether we should disable "Continue" button when no hosts are selected. Currently, it's not blocking you …

fix: Show allowlist dialog as modal when action is required

---

src/utils/harToProxyData.ts

Currently, when trying to import externally recorded HAR, you'll get an error. This is caused by trying to decode a non-base64-encoded response content. Using `safeAtob` will allow us to support both encoded and non-encoded HARs. 
1. Using your browser (I've used Chrome) visit a website with devtools opened, save the HAR from network tab
2. Import HAR into k6 studio

fix: Import external HAR

---

src/views/Generator/GeneratorSidebar/GeneratorSidebar.tsx
src/views/Home/Home.tsx

1. When there's a script error, the generator sidebar tabs can get covered
2. Add padding to home screen

fix: Minor ui bugs

---

src/components/Form/FileUploadInput.tsx
src/components/Settings/ProxySettings.tsx
src/components/Settings/RecorderSettings.tsx
src/components/Settings/SettingsDialog.tsx
src/components/Settings/SettingsSection.tsx
src/components/Settings/UsageReportSettings.tsx

This PR changes the Settings dialog by separating sections into tabs. This provides a cleaner user interface as we add more functionalities to the Studio and enable users with custom settings.
- Make the state of the settings dialog invalid
- Attempt to submit
- Check that tabs with errors are automatically selected and, inputs with errors automatically get focus
https://github.com/user-attachments/assets/a01c999c-a401-4a8e-a255-2ec6c0097c92

feat: organize settings dialog with tabs

---

src/main.ts
src/proxy.ts

When the proxy fails to start, the only line outputted to the log file is the following:
```.log
[2024-11-07 10:53:51.755] [error] Error logged during startup, exiting...
```
This happens because mitmproxy outputs some errors to stdout and, we are not capturing them.
With the changes in this PR, the log file will look like this when the proxy port is already in use, but additional information will be captured regardless of the error:
```log
[2024-11-07 10:48:52.998] [error] Error logged during startup, exiting...
[2024-11-07 10:48:52.999] [error] [10:48:52.998] [Errno 48] HTTP(S) proxy (upstream mode) failed to listen on *:6001 with [Errno 48] error while attempting to bind on address ('0.0.0.0', 6001): address already in use
[2024-11-07 10:48:53.000] [error] Try specifying a different …
```

feat: capture additional logs for proxy

---

resources/group_snippet.js

⚠️ Please check that Validator works with different test scripts

refactor: Avoid param reassignment in group_snippet

---

resources/group_snippet.js

See [this comment thread](https://github.com/grafana/k6-studio/pull/303#discussion_r1834083666)
Make sure Validator works as expected
https://github.com/grafana/k6-studio/pull/303

refactor: Use IIFE in group_snippet

---

src/main.ts
src/settings.ts

On Windows, the settings file was noticed to be created without any content, likely due to other issues during initialization that can be observed in the full log file found at https://github.com/grafana/k6-studio/issues/345.
This PR makes changes that ensure that the application initializes with valid settings when the JSON file is corrupted.
In any platform, using this branch:
- Delete the `k6-studio-dev.json` file
- Initialize the app and check that the default configuration is loaded
- Remove the content of `k6-studio-dev.json` (make it 0 bytes or anything else than a JSON)
- Initialize the app and check that the default configuration is loaded
Resolves https://github.com/grafana/k6-studio/issues/345

fix: prevent app from crashing when settings file is invalid

---

src/main.ts
src/settings.ts

The window state is not being persisted when the Settings dialog is open and, you move or resize the main window. This PR makes changes to the `saveSettings` function to ensure only fields that are being submitted from the form are being overwritten.
- Launch the app
- Open the Settings dialog
- Move and resize the main window
- Make any other change on the settings dialog,such as changing the proxy port or changing the theme
- Submit your changes
- Close the app and check that window state and remaining settings were properly persisted

ensure window state is tracked when settings dialog is open

---

.eslintrc.cjs
.github/workflows/release.yml
.gitignore
install-k6.js
package-lock.json
package.json

The binaries for `k6` have been removed and now the specified version of `k6` is retrieved from the k6 github repository during the release ci process. The version is specified by a repository variable called `K6_VERSION`.
Due to this, the binary is also missing in `dev` so the `npm install` has been augmented with a script to retrieve the binary if it's missing.
_note: The version for `dev` is specified inside of the `install-k6.js` file at this time, so the version is specified in 2 places._
- Clone the repository and `npm install` making sure you have `k6` installed after it.
- Trigger a manual release from this branch and test that it includes k6.
Closes #327

feat: bundle latest k6 on build

---

src/main.ts
src/preload.ts
src/views/Recorder/Recorder.tsx
src/views/Recorder/Recorder.utils.ts

This PR provides a more meaningful file name for the recording based on the starting URL.
- start a new recording
- input the starting URL
- stop the recording
- check that the generated HAR file contains hostname of the starting URL
- check that omitting the starting URL does not include any prefix
Resolves https://github.com/grafana/k6-studio/issues/306

feat: add hostname as prefix of har filename

---

src/views/RecordingPreviewer/RecordingPreviewer.tsx

When viewing an existing recording and clicking "New recording" the viewed recording gets deleted. This is destructive and unexpected behavior. 
Steps to reproduce:
1. Open existing recording
2. Click "New recording" button.
**Expected behavior:**
Existing recording is preserved and new recording starts.
**Actual behavior:**
Existing recording gets deleted

fix: "New recording" button discards existing recording

---

src/components/FileTree/types.ts
src/components/HighlightedText.tsx
src/components/Layout/Sidebar/Sidebar.hooks.ts
src/components/MethodBadge.tsx
src/components/ResponseStatusBadge.tsx
src/components/WebLogView/Filter.hooks.ts
src/components/WebLogView/Row.tsx
src/components/WebLogView/WebLogView.tsx
src/types/fuse.ts
src/types/index.ts
src/utils/fuse.ts

Highlight matched values when searching requests. Thank @allansson for laying the groundwork and extracting reusable highlight component! 🙌 I've tweaked the colors a bit to make it easier to see the highlighted parts. 
Test search in recorder, generator, and validator - verify matches are highlighted. 
Resolves https://github.com/grafana/k6-studio/issues/322

feat: Highlight search matches

---

src/codegen/codegen.test.ts
src/rules/correlation.ts
src/rules/rules.ts
src/schemas/rules.ts
src/store/generator/fixtures.ts
src/store/generator/slices/rules.ts
src/test/factories/generator.ts
src/test/fixtures/parameterizationRules.ts
src/utils/rules.ts
src/views/Generator/RuleEditor/RuleEditor.tsx
src/views/Generator/TestRuleContainer/TestRule/TestRule.tsx
src/views/Generator/TestRuleContainer/TestRule/TestRuleActions.tsx
src/views/Generator/TestRuleContainer/TestRule/TestRuleInlineContent.tsx

This PR introduces the ability to disable/enable a test rule. Disable rules will not be generated by the script.
- Create a new Test Rule
- Disable the rule and check that it was not generated by the script
- Re-enable the same rule and check that it is now generated by the script
Resolves https://github.com/grafana/k6-studio/issues/313

feat: ability to disable a rule

---

src/components/WebLogView/Row.tsx
src/components/WebLogView/WebLogView.tsx
src/components/WebLogView/WebLogView.utils.ts
src/types/index.ts

This PR adds a new `Type` column to the `WebLogView` component to differentiate static assets from dynamic requests.
- Toggle the "Show static assets" switch
- Check that the Type column shows the appropriate label for each request
Resolves https://github.com/grafana/k6-studio/issues/325

feat: add type column to WebLogView

---

src/components/Settings/LogsSettings.tsx
src/components/Settings/Settings.hooks.ts
src/components/Settings/SettingsDialog.tsx

1. Open the settings dialog
2. Check if tabs still work
3. Try changing a setting and saving it

chore: Use tanstack query for settings

---

src/components/Layout/Sidebar/Sidebar.tsx

See attached screenshots
* Resize the window to the min supported height
* Make sure you have enough files for the scrollbar to appear
* Verify that the last item is clearly visible
Before
After

fix: Last item scripts list isn't always accessible

---

src/browser.ts

On Windows, if the user doesn't provide a URL before starting a recording, the browser shows the Chrome folder.
On a windows machine:
1. Open the app
2. Go to Recorder
3. Click `Start recording` while leaving the `Starting URL` blank
4. Verify that the browser is launched with an empty page

fix(windows): Chrome folder is shown when no starting URL is provided

---

src/components/Collapsible.tsx
src/components/WebLogView/WebLogView.tsx
src/views/Recorder/Recorder.tsx
src/views/Recorder/RequestsSection.tsx

Closes https://github.com/grafana/k6-studio/issues/321
* Open the validator dialog
* Run a script
* Verify that the group sections have expected caret state

fix: Caret icon doesn't change state in Validator dialog

---

src/components/Monaco/EditorToolbar.tsx
src/components/Monaco/ReactMonacoEditor.tsx
src/components/Monaco/languages/log.ts
src/components/Monaco/themes/k6StudioDark.ts
src/components/Monaco/themes/k6StudioLight.ts
src/components/WebLogView/ResponseDetails/Preview.tsx

This PR adds basic syntax highlight for the log viewer in the Settings dialog, making it easy to read and scan issues.
- Check the Logs tab in Settings dialog using Light and Dark themes
Resolves https://github.com/grafana/k6-studio/issues/387

feat: syntax highlight for log viewer

---

.github/workflows/release.yml

This specifically builds the x64 version of the app separately for `intel` macs.
Although an `universal` build is possible, it doubles the size of the app for the end user.

fix: intel mac app

---

src/views/Generator/GeneratorControls/GeneratorControls.tsx
src/views/Generator/GeneratorSidebar/RequestList.tsx
src/views/Generator/RecordingSelector.tsx

This PR moves the Recording dropdown from the "Requests" tab in the Preview section to the top bar on the Generator page.
Smaller window size:
Resolves https://github.com/grafana/k6-studio/issues/317

feat: move recording selector position

---

.github/workflows/release.yml
package-lock.json
package.json
vite.preload.config.ts
vite.renderer.config.ts

This PR fixes an issue where sourcemaps were not being uploaded to Sentry during a release.
When looking at the release logs we can see the following warning:
```
[sentry-vite-plugin] Warning: No project provided. Will not create release. Please set the `project` option to your Sentry project slug.
```
We can also see that the `SENTRY_PROJECT` and `SENTRY_ORG` variables are not being read properly from the repo settings:
```
SENTRY_DSN: ***
SENTRY_AUTH_TOKEN: ***
SENTRY_ORG:
SENTRY_PROJECT:
```
This caused `@sentry/vite-plugin` not to know which Sentry project to associate the sourcemaps with.

fix: sourcemaps not uploading to Sentry

---

.husky/pre-commit
package.json

We use `npm` in k6 studio, but the pre-commit hook still references `yarn`, which could lead to not being able to create commits if you don't have `yarn` installed
* Checkout the branch and make sure you can add commits to it and the pre-commit hook runs (adding an obvious eslint issue should be an easy way to do it)

chore: Remove yarn usage from pre-commit hook

---

package-lock.json
package.json
src/App.tsx
src/components/DevToolsDialog.tsx
src/components/Feature.tsx
src/components/Layout/Sidebar/Sidebar.tsx
src/store/features/index.ts
src/store/features/useFeaturesStore.ts
src/types/features.ts

* Enter the "konami code" (`up-up-down-down-left-right-left-right-b-a`)
* Toggle the `data-files` feature
* Check that the `Data files` section is displayed in the sidebar

chore: Add basic feature flags support

---

src/rules/correlation.utils.ts
src/rules/selectors/text.test.ts
src/rules/selectors/text.ts
src/rules/shared.ts
src/schemas/generator/v1/rules.ts
src/types/rules.ts
src/views/Generator/RuleEditor/SelectorField.constants.ts
src/views/Generator/RuleEditor/SelectorField.tsx
src/views/Generator/TestRuleContainer/TestRule/TestRuleSelector.tsx

Add text selector to exact string match replacements. Previously you'd have to use a workaround with regex selector: regex: (value_to_be_placed). 
This selector applies to parameterization rule and correlation rule custom replacer, but not correlation extractor, because it doesn't make sense to correlate on static value.
- Test with parameterization rule: try both "text value" and "variable" replacement
- Test with custom replacer in correlation rule
Resolves https://github.com/grafana/k6-studio/issues/315

feat: Add text selector

---

src/components/JsonPreview.tsx
src/components/WebLogView/ResponseDetails/Preview.tsx

Initially, I wanted to re-use json preview for data files, but after some prototyping, I decided to use a simple Table instead. I thought I'd still create this PR as it should make it easier to re-use this in other places.
Check that preview of JSON payloads/response bodies works as expected

refactor: Extract Json preview into separate component

---

src/components/WebLogView/Cookies.tsx
src/components/WebLogView/RequestDetails/RequestDetails.tsx
src/components/WebLogView/ResponseDetails/ResponseDetails.tsx

Use the same components as `Headers` for better UI consistency
Check that cookies are displayed correctly
Before
After

style: Unify cookie and header previews

---

src/components/FileTree/File.tsx

fix: Filename tooltip obscures other files

---

src/schemas/generator/v1/thresholds.ts
src/store/generator/selectors.ts
src/store/generator/slices/thresholds.ts
src/test/factories/generator.ts
src/types/thresholds.ts
src/views/Generator/TestOptions/Thresholds/ThresholdRow.tsx
src/views/Generator/TestOptions/Thresholds/Thresholds.tsx
src/views/Generator/TestOptions/Thresholds/Thresholds.utils.ts

This PR implements logic to validate and persist the state of the thresholds to the Generator file.
- 🔨 Codegen pending
- 🔨 UI polishing pending
- Type the konami code and enable Thresholds
- Open a generator and configure some thresholds
- Check that the generator state is now dirty
- Save the generator and check that the data is persisted

internal(Thresholds): Validate and save to Generator file

---

src/components/Layout/Sidebar/Sidebar.hooks.ts
src/components/Layout/Sidebar/Sidebar.tsx
src/hooks/useCreateGenerator.test.ts
src/hooks/useCreateGenerator.ts
src/main.ts
src/preload.ts
src/types/generator.ts
src/utils/file.ts
src/utils/rules.ts
src/utils/typescript.ts
src/views/Generator/Generator.hooks.ts
src/views/Generator/Generator.utils.ts
src/views/Home/Home.tsx
src/views/Recorder/Recorder.tsx
src/views/Recorder/Recorder.utils.ts
src/views/RecordingPreviewer/RecordingPreviewer.tsx

- Make auto-generated file names shorter and reduce noise, by removing the timestamp and using optional increment at the end.
- Remove `GeneratorFile` as it's become redundant
- Stringify HAR/Generator data in the main process
Verify that the following works as before (apart from the new filenames):
- Create an new generator, then do it again on the same date
- Create a few new recordings with the same starting URL
- Create a new recording without a starting URL
- Try re-configuring a generator and saving changes

feat: Simpler default file names

---

src/components/FileTree/File.tsx
src/components/FileTree/FileContextMenu.tsx

Make it easier to discover file actions by adding a menu, that can be opened with keyboard or mouse click
Verify that both context menu (on right click) and this new menu work and look identical.

feat: Show actions menu button when hover over file item

---

src/codegen/codegen.test.ts
src/components/Form/ControlledSelect.tsx
src/views/Generator/TestOptions/TestOptions.tsx
src/views/Generator/TestOptions/Thresholds/ThresholdRow.tsx
src/views/Generator/TestOptions/Thresholds/Thresholds.tsx
src/views/Generator/ValidatorDialog.tsx

This PR addresses some UI inconsistencies and bugs on the Thresholds feature.
- Tooltip in the URLs Select component
- Rename "Stop" column to "Stop test"
- Fix `isRunning` state in Validator Dialog when a threshold crosses
- Remember last selected tab in Test Options
- Enable the Thresholds feature
- Check the Thresholds tab in Test Options

internal(Thresholds): polish UI

---

forge.config.ts
package.json

Fix https://github.com/grafana/k6-studio/issues/460
Fix https://github.com/grafana/k6-studio/issues/486
The build for both mac architectures is done on an arm machine and that would make the packager packager only the `arm64` folder even on an `x86_64` architecture, this PR fixes that by including both folders on mac with a small cost of `71~MB` increase of application size

fix: intel mac proxy

---

extension/src/recorder.ts
install-k6.js
src/codegen/browser/test.ts
src/schemas/recording/v1/browser.ts
src/views/Recorder/BrowserEventLog.tsx

This PR adds support for capturing form submit events. Submitting a form will now result in a mouse click on the submit button that caused the submit.
1. Record a page that uses forms, e.g. https://test.k6.io/members.php
2. Submit the form by pressing a submit button.
3. Submit the form by pressing Enter in an input.
4. Export and run a script.
> #### Note: I noticed that I got an occasional "Cannot find context with specified id" when running the script. I tried bumping k6 to 0.56.0 and it went away. 🤔

feat: Record, display and generate code for form submit events

---

src/components/FileTree/File.hooks.ts
src/components/FileTree/File.tsx
src/components/FileTree/FileList.tsx
src/components/FileTree/InlineEditor.tsx
src/main.ts
src/preload.ts

Closes https://github.com/grafana/k6-studio/issues/472
* Fix https://github.com/grafana/k6-studio/issues/472
* Fix a bug with overwriting existing files when renaming
* Try renaming files - it should work as expected
* Try using a filename that already exists - the rename operation should fail with a toast notification shown to the user

fix: Old name is shown when trying to rename file again

---

src/constants/files.ts
src/constants/workspace.ts
src/main.ts
src/preload.ts
src/script.ts
src/utils/workspace.ts
src/views/Generator/ValidatorDialog.tsx
src/views/Validator/Validator.hooks.ts
src/views/Validator/Validator.tsx

* Fix the issue of not being able to validate tests on Windows in some cases
* Recently, we changed how test runs were initiated to support external dependencies in future. We used `symlink` to create a temporary symlink, which didn't work on Windows under some conditions (we suspect it had something to do with the user role/permissions).
* We switched to a different approach, one that should also address a recently reported issue with validating external scripts with dependencies
* Fix the issue of not being able to see the external script content
* Fix the issue of not being able to validate external scripts with dependencies (data files, external modules, etc)
- Test both `Validator` and `Validator dialog`
- Make sure external scripts work as well
- Test on Windows
Hopefully, it will …

fix: Validator requires admin role on Windows

---

src/codegen/codegen.test.ts
src/codegen/codegen.ts
src/rules/parameterization.test.ts
src/rules/parameterization.ts

This PR fixes an issue where the parameterization custom code is declared inside a group making it unavailable in subsequent groups.
```.ts
...
group("Group 2", function () {
function getParameterizationValue0() { ... }
})
group("Group 1", function () {
// getParameterizationValue0 is not available here
})
```
To fix this issue, custom codes generated by parameterization were moved to upper scope.
- Create a couple of parameterization rules with custom code
- Check that the code is generated outside of groups
Resolves https://github.com/grafana/k6-studio/issues/457

fix: parameterization custom code is not defined

---

src/codegen/codegen.ts
src/components/Layout/Sidebar/Sidebar.tsx
src/constants/files.ts
src/main.ts
src/preload.ts
src/rules/parameterization.ts
src/schemas/generator/v1/rules.ts
src/views/DataFile/DataFile.tsx
src/views/Generator/RuleEditor/ParameterizationEditor/FileSelect.tsx
src/views/Generator/RuleEditor/ParameterizationEditor/ValueEditor.tsx
src/views/Generator/RuleEditor/ParameterizationEditor/VariableSelect.tsx
src/views/Generator/TestOptions/DataFiles.tsx
src/views/Generator/TestOptions/VariablesEditor.tsx
src/views/Generator/TestRuleContainer/TestRule/TestRuleSelector.tsx

Add a way to select value from file in Parameterization rule editor - this PR and the finishing UI touches are the biggest missing piece stopping us from making the feature public.
1. Enable the `data-files` feature
2. Import a JSON/CSV file
3. Open a generator
4. Add the file in `Test options` <- the UI will be updated
5. Add a parameterization rule and select `Data file` in selector
6. Verify that the generated script works

internal(Data files): Add data files support in Parameterization rules

---

src/components/WebLogView/RequestDetails/QueryParams.tsx
src/components/WebLogView/RequestDetails/RequestDetails.tsx

fix: Query params list style is inconsistent with other tabs

---

src/codegen/codegen.test.ts
src/codegen/options.test.ts
src/codegen/options.ts
src/schemas/generator/v0/index.ts
src/schemas/generator/v1/loadZone.ts
src/schemas/generator/v1/testOptions.ts
src/store/generator/slices/testOptions/loadZones.ts
src/test/factories/generator.ts
src/test/factories/loadZones.ts
src/utils/generator.ts
src/views/Generator/TestOptions/LoadZones/LoadZoneRow.tsx
src/views/Generator/TestOptions/LoadZones/LoadZones.tsx
src/views/Generator/TestOptions/LoadZones/LoadZones.utils.tsx

This PR continues the implementation of the Load Zones features and includes:
- improved error messaging
- renamed `loadZones.loadZones` in the generator to `loadZones.zones` for better DX
- code generation
The following are still pending:
🛠️ some type of messaging is needed in the Load Zones tab when users are not authenticated with Cloud
🛠️ improve UX in regards to the Even/Manual button as raised in https://github.com/grafana/k6-studio/pull/518
- enable the "load-zones" feature
- add/remove load zones and check that the code is properly generated
- (optional) run the script in Grafana cloud
https://github.com/user-attachments/assets/ab05f917-3c80-4b12-8241-e6d985e44b3d

internal(Load Zones): Generate code for load zones

---

src/App.tsx
src/browser.ts
src/components/Form/FileUploadInput.tsx
src/components/Layout/ActivityBar/ProxyStatusIndicator.tsx
src/components/Layout/ActivityBar/SettingsButton.tsx
src/components/Settings/RecorderSettings.tsx
src/components/Settings/SettingsDialog.tsx
src/components/TextButton.tsx
src/hooks/useProxyStatus.ts
src/hooks/useSettings.ts
src/main.ts
src/preload.ts
src/store/ui/useStudioUIStore.ts
src/views/Recorder/EmptyState.tsx

Closes https://github.com/grafana/k6-studio/issues/515
For the browser stuff, mock the handler in main.
To test the proxy warning, kill the proxy process.

fix: It's possible to start a recording with no supported browser installed

---

src/hooks/useImportDataFile.ts
src/main.ts
src/script.ts
src/views/Generator/TestData/DataFiles.tsx

* Add a way to import data files directly from the Test Data popover
* Show a toast on success
Try importing a data file from the test data popover

feat: Add a way to import data files directly from Test Data popover

---

src/handlers/auth/states.ts

This PR removes encryption using `safeStorage` because the user was constantly prompted to give permission for the application to use it.
> #### Note: this is technically a breaking change. You will need to sign in and out before using the account in the upcoming cloud run feature.
Login to a stack.

internal: Fixed requests to access secrets.

---

src/views/Generator/RuleEditor/CorrelationEditor.tsx
src/views/Generator/RuleEditor/ParameterizationEditor/ParameterizationEditor.tsx
src/views/Generator/RuleEditor/RuleEditor.tsx

fix: Columns in Rule Editor don't have clear separation

---

src/store/features/useFeaturesStore.ts
src/types/features.ts
src/views/Generator/TestOptions/TestOptions.tsx

This PR removes the feature flag for the Load Zones feature, making it fully available for users.
- Open a Generator > Test Options
- Add and remove load zones
- Check that load zones are generated in the script
- (Optionally) Test the script in Grafana Cloud
Resolves https://github.com/grafana/k6-studio/issues/455

feat: Add support for Load Zones in Test Options

---

src/components/Layout/ActivityBar/SettingsButton.tsx
src/components/Settings/SettingsDialog.tsx
src/components/Settings/types.ts
src/store/ui/useStudioUIStore.ts
src/views/Recorder/EmptyState.tsx

This PR changes how the state of the Settings dialog is controlled, allowing it to open with a specific tab selected. This change improves usability in the Recording screen when a browser can't be found or when a browser fails to launch (https://github.com/grafana/k6-studio/pull/535)
- Mock this line to `return false`
https://github.com/grafana/k6-studio/blob/cb5a7758f8b17d692f46b410835603eaec458aa6/src/main.ts#L531
- Open the Recorder and click "Settings"
- Check that the Recorder tab is automatically selected
https://github.com/user-attachments/assets/51827e98-8caa-41a0-b577-1be88c504e84
Resolves https://github.com/grafana/k6-studio/issues/525

feat: Make it possible to open Settings with specific tab selected

---

vite.main.config.ts

This PR configure the app so that building it will use production environment by default.
Run the app, sign in in to a stack and run a test. The app should:
* Use grafana.com when signing in
* Use grafana.com when trying to sign up
* Open **_yourstack_**.grafana.net when starting a test run

build: Configure oauth client and urls for production

---

src/components/FileTree/File.hooks.ts
src/components/FileTree/File.tsx

Closes https://github.com/grafana/k6-studio/issues/506
1. Open a generator
2. Change its configuration (the easiest thing to do might be disabling a rule)
3. Try renaming the file - it should work without creating an extra file

fix: Renaming generator with unsaved changes creates extra file

---

src/main.ts

The extension for generator files has been changed from `.json` to `.k6g`.
To facilitate migrations, json files in the Generator folder are automatically transformed into k6g
Open the app, check that your old Generators now have the `.k6g` extension.
**note:** you might want to backup your project folder until this gets merged

feat: migrate generator extension json -> k6g

---

src/views/Generator/ValidatorDialog.tsx
src/views/Recorder/RequestsSection.tsx

It was reported that the spinner in the validator dialog is not visible as the user's attention is usually focused on the left side of the screen. This PR adds a spinner besides the Validator title, making it easier to identify when a script is running.
Resolves https://github.com/grafana/k6-studio/issues/544

feat: Improve spinner visibility in Validator dialog

---

src/script.ts

fix(Validator): Scripts with no k6/execution import cannot be run

---

src/handlers/auth/index.ts
src/handlers/cloud/index.ts
src/handlers/index.ts
src/main.ts
src/utils/electron.ts

When closing app and trying to open it from menu bar on macOS, the app would crash with error:
This happens because we try to initialize handlers again after resuming app, but closing into menu bar doesn't clear handlers. 
To solve it:
- Removed handler initialization dependency on `browserWindow`, read from event instead
- Moved handler initialization into root of main.ts
1. Start studio
2. Close studio by clicking "x" in the app window
3. Start studio from menu bar
Expected behavior:
App should reopen
Actual behavior:
Nothing happens, error in terminal
Verify all auth/cloud related functionality works as expected.

fix: App not opening after closing on macOS

---

src/ErrorElement.tsx
src/components/Settings/TelemetrySettings.tsx
src/views/Generator/TestOptions/LoadZones/LoadZones.tsx
src/views/Generator/TestOptions/Thresholds/Thresholds.tsx

Use the ExternalLink component for, well, external links.
This leaves just 2 places where `openExternalLink` is used directly, but since those are in a dropdown menu, I couldn't used this component.
Verify that the links work

chore: Use ExternalLink component for docs and GitHub links

---

src/components/Layout/ActivityBar/ProxyStatusIndicator.tsx
src/main.ts
src/views/Recorder/EmptyState.tsx

This PR implements the ability for users to control the proxy (start or stop) through the sidebar.
Start and stop the proxy on the sidebar and check that the status changes as expected.
https://github.com/user-attachments/assets/27957710-f564-40d7-8c6d-78790ca63f32
Resolves https://github.com/grafana/k6-studio/issues/329

feat: Ability to control proxy status

---

src/components/WebLogView/Filter.hooks.ts
src/components/WebLogView/RequestDetails/Headers.tsx
src/components/WebLogView/ResponseDetails/Headers.tsx

- Highlight URL and method in request inspector when searching
- Add "headers" heading to separate general info from headers (similar to devtools)
Search and verify matches are highlighted as expected.
Resolves https://github.com/grafana/k6-studio/issues/520

fix: Highlight URL search matches in request inspector

---

src/components/Layout/ActivityBar/HelpButton.tsx
src/main.ts
src/menu.ts
src/preload.ts
src/utils/bugReport.ts

`Report an issue` now pre-fills the OS and version fields. 
Know limitations:
- There doesn't seem to be a reliable way to get the linux distro name 
Testing instructions:
- Check that `Report new issue` actually opens the new issue form with the `bug` template
- Check that the OS and Version fields are filled

feat: Pre-fill OS and app version when reporting issues

---

extension/src/frontend/index.ts
src/components/BrowserEventList/EventDescription/EventDescription.tsx
src/components/BrowserEventList/EventDescription/InputChangedDescription.tsx
src/schemas/recording/v1/browser.ts

For security reasons, it's a bad idea to display passwords in plain text in the event log. 
The data is still recorded, but this way we at least stop the password from being leaked by someone looking over the shoulder.
1. Go to a page with a _proper_ password input (unlike those in quickpizza).
2. Change the value of the password input.
3. Check the browser event log.
4. The logged event should have its value masked.
https://github.com/user-attachments/assets/5a845531-a7a8-455a-aadd-96adafdfe099

fix(browser): Values from password inputs are shown in plain text in the event log

---

src/handlers/har/index.ts
src/handlers/har/preload.ts
src/handlers/har/types.ts
src/handlers/index.ts
src/main.ts
src/preload.ts
src/utils/fileSystem.ts

This PR kicks off the work of decoupling the `main.ts` file by separating the IPC handlers into their own namespace/folders. This work will be broken down into many pieces so it's easier to review and validate the changes.
Validate the following:
- Opening a HAR file works as expected
- Stopping a recording saves a HAR file successfully
- Importing a HAR file into an existing generator works as expected

refactor(Split main): Move HAR handlers out of main.ts

---

src/components/WebLogView/ContentPreview.tsx
src/components/WebLogView/RequestDetails/Payload.tsx
src/components/WebLogView/RequestDetails/utils.ts
src/components/WebLogView/ResponseDetails/Content.tsx

This PR adds support for users to inspect raw data and preview JSON for request payloads, similar behaviour that exist in responses.
- Inspect POST/PUT/DELETE/PATCH requests that contain JSON payload
- Check that the JSON preview and raw content is available
https://github.com/user-attachments/assets/c1ac4df2-9b5d-4f84-859e-d1bfce6dab46
Resolves https://github.com/grafana/k6-studio/issues/324

feat: Add support for content preview in request payload

---

forge.env.d.ts
src/browser.ts
src/handlers/browser/index.ts
src/handlers/browser/preload.ts
src/handlers/browser/types.ts
src/handlers/index.ts
src/k6StudioState.ts
src/main.ts
src/preload.ts
src/proxy.ts

This PR continues the work of refactoring the main process by moving the `browser` handlers out of the `main.ts` file.
In addition to the IPC handlers, this PR introduces a global variable `k6StudioState` to help managing global variables that are being used across multiple handlers.
- Check that the browser works as expected by starting and stopping a recording
- Check that the proxy status changes as expected

refactor(split main): Move browser handlers out of main.ts

---

.github/workflows/release-test-version.yml
update_version.py

Adds a github action to build a test version of k6 studio without having to jump through hoops.
The action will require the user to specify a `version` to be used for that specific test release.

chore: release test version action

---

src/handlers/index.ts
src/handlers/script/index.ts
src/handlers/script/preload.ts
src/handlers/script/types.ts
src/main.ts
src/preload.ts

This PR continues the work of moving the IPC handlers out of the `main.ts` file.
Test areas where `script` handlers are used:
Validator:
- Open an existing script from the sidebar
- Validate the script
- Stop the script execution
- Open an external script
Generator:
- Export a script
- Validate the script
- Stop the script execution

refactor(split main): Move script handlers out of main.ts

---

extension/src/frontend/view/EventDrawer.tsx
extension/src/messaging/transports/background.ts
src/browser.ts

Text assertions break when using the back button.
1. Go to a page
2. Click a link that navigates you to another page
3. Click back
4. Add a text assertion
5. Check that the text assertion is added to the event list

fix: Text assertions break when using back button

---

src/components/GhostButton.tsx
src/views/Generator/GeneratorControls/GeneratorControls.tsx
src/views/Generator/GeneratorTabs/ScriptPreview.tsx
src/views/Validator/ValidatorControls.tsx
src/views/Validator/ValidatorEmptyState.tsx

Closes https://github.com/grafana/k6-studio/issues/609
- Stop proxy
- Verify that you cannot start a validation run (both in Validator and in Generator)

fix: Validator run is available when proxy is offline

---

src/store/generator/slices/recording.utils.ts
src/views/Generator/Allowlist/Allowlist.tsx
src/views/Generator/Allowlist/AllowlistCheckGroup.tsx
src/views/Generator/Allowlist/AllowlistDialog.tsx

This PR pre-selects the first URL in `AllowlistDialog`. This is not limited to the user inputting a host when starting a recording.
In addition to this, common domain names requested by Chrome browser are reordered to the end of the list.
- Open a generator that doesn't have any hosts selected
- Check that the first item in the list is selected (which should be the first host recorded in the HAR file)
- Check that hosts that belong to `googleapis.com` and `google.com` are moved to the end of the list
- Check that the user can unselected the pre-selected domain
- The pre-selected domain feature should only work when opening another generator or changing the recording within the generator window
https://github.com/user-attachments/assets/43904fd4-1d90-493c-8a5a-92b9e3447de9
Resolves …

feat: Pre-select first host in rercording

---

Dockerfile
extension/src/background/navigation.ts
extension/src/frontend/index.ts
extension/src/frontend/view/TextAssertionEditor.tsx
src/codegen/browser/test.ts
src/components/BrowserEventList/EventDescription/ClickDescription.tsx
src/components/BrowserEventList/EventDescription/EventDescription.tsx
src/components/BrowserEventList/EventDescription/InputChangeDescription.tsx
src/components/BrowserEventList/EventDescription/PageNavigationDescription.tsx
src/components/BrowserEventList/EventIcon.tsx
src/schemas/recording/v1/browser.ts

While working on adding additional types of assertions I came to the conclusion that it was better to have a single browser event for all assertions and let the event contain the specifics of the assertion.
I want to get this merged before releasing so that I won't have to add a migration for it.
1. Start a recording
2. Add a text assertion
3. Stop recording
4. Open browser events list
5. Export script
6. Verify that generated script calls `toContainText`

internal(browser): Unified schema for assertion events

---

src/components/WebLogView/RequestDetails/utils.ts

Payload preview doesn't work when a numeric value is replaced by a correlation variable, for example:
```json
{ "id": ${correlation_vars['correlation_0'] }
```
In Payload preview, we parse the string as JSON, but the injected variable makes in invalid. 
To solve this I've added a function to wrap variable expressions in quotes, that's not ideal because it makes it look like the value injected would be a string, but at least it doesn't break the preview. We might want to revisit this in the future and remove JSON parse altogether, but we'd need a new way to prettify it. 
Use attached recording and generator.
Steps to reproduce:
1. In the generator, inspect `POST /api/ratings` request 
2. Click on payload.
**Expected result**: payload preview with injected correlation value is displayed …

fix: Preview payload when correlating numeric properties

---

src/handlers/index.ts
src/main.ts

We introduce a change that tries to re-register IPC handlers when the main window is re-created. This PR reverts that change.
- Launch the app on macOS
- Close the main window
- Restore it from the dock
- Check that the window was properly recreated

internal: main window cannot be restored on macOS

---

src/handlers/index.ts
src/handlers/proxy/index.ts
src/handlers/proxy/preload.ts
src/handlers/proxy/types.ts
src/handlers/settings/index.ts
src/k6StudioState.ts
src/main.ts
src/preload.ts
src/proxy.ts
src/settings.ts

This PR moves the proxy handlers, preload and related helper functions out of `main.ts`. No functional changes were made.
- Proxy starts and stops as expected
- Proxy status is properly reported to the UI
- Script validator works as expected
- Proxy settings are properly saved

refactor(Split main): Move proxy handlers out of main.ts 

---

extension/src/frontend/view/ElementInspector.hooks.ts
extension/src/frontend/view/Overlay.tsx
extension/src/frontend/view/RemoteHighlights.hooks.ts
extension/src/frontend/view/TextAssertionEditor.hooks.ts
extension/src/frontend/view/TextAssertionEditor.tsx
extension/src/frontend/view/utils.ts

This PR fixes element highlights getting out of sync, i.e. no longer overlaying elements, when scrolling or resizing the window.
1. Start a recording.
2. Use the inspect element tool and scroll while hovering an element
- The highlight should stick to the element (until it highlights another element)
3. Highlight text using the Add text assertion tool.
- Highlight should stick when scrolling up/down
- Highlight should stick when resizing window

internal(browser): Element highlights get out of sync with content when resizing/scrolling page

---

src/handlers/dataFiles/index.ts
src/handlers/dataFiles/preload.ts
src/handlers/dataFiles/types.ts
src/handlers/index.ts
src/main.ts
src/preload.ts

This PR moves the data file handlers and preload functions to its own namespace in `./src/handlers`. No functional changes were made.
Check that the following works as expected:
- Import a data file
- Preview of a data file

refactor(Split main): Move data file handlers out of main.ts

---

package-lock.json
package.json
src/views/Recorder/RecordingInspector.tsx

This PR adds a beaker icon to the Browser Events tab in the recording views so that it's more obvious that the feature is in public preview.
1. Start a recording.
2. Check that the Browser Events tab has a beaker icon
3. Stop the recording
4. Check that the Browser Events tab still has a beaker icon.

internal(browser): Add beaker icon to Browser Events tab

---

extension/src/frontend/view/RemoteHighlights.hooks.ts

Users can crash the in-browser UI by entering an invalid selector in the text assertions dialog.
1. Start a recording
2. Select the text assertion tool
3. Highlight some text
4. Change the selector to something invalid.
The UI should not crash.

internal(browser): In-browser UI crashes when entering an invalid selector

---

src/handlers/app/index.ts
src/handlers/app/preload.ts
src/handlers/app/types.ts
src/handlers/index.ts
src/k6StudioState.ts
src/main.ts
src/main/window.ts
src/preload.ts

This PR is the last one from the series "Move handlers out of main.ts" and addresses the `app` handlers and preload functions. With this final change, we no longer have a `main.ts` file with IPC handlers.
One more PR is coming up that moves some files from the root folder to the `./src/main` folder, making the organization a bit clearer.
- Check that the splashscreen shows and closes as expected
- Modify a generator and close the app without saving. Check that the app prompts you to save before closing

refactor(Split main): Move app handlers out of main.ts

---

.github/workflows/release-test-version.yml
.github/workflows/release.yml

Separates the build action for macos on different runners depending on architecture avoiding the risk of consuming all resources of the runner and making it hang.

internal: fix macos build action

---

index.html

Closes https://github.com/grafana/k6-studio/issues/643
* Start k6 studio locally and pay close attention to the in-app text
* Verify that the font doesn't switch from a fallback font to Inter

chore: Preload fonts

---

src/components/Settings/ProxySettings.tsx
src/main/proxy.ts
src/main/settings.ts
src/schemas/settings/index.test.ts
src/schemas/settings/v1/index.ts
src/views/Recorder/EmptyState.tsx

This PR introduces a new option in the proxy settings that allows users to [bypass SSL verification](https://docs.mitmproxy.org/stable/concepts-options/#ssl_insecure) to test certain environments when required.
A section in the Troubleshoot doc was also added in https://github.com/grafana/k6-docs/pull/1940
- Launch a new instance of mitmproxy:
```sh
mitmdump --mode regular@7005
```
- Change k6 Studio proxy mode to "upstream" and Server URL to "http://localhost:7005"
- Keep the "Skip SSL/TLS certificate validation" __unchecked__
- Start a new recording
- Check that the browser returns a 502 Certificate verify failed error
- Change k6 Studio proxy mode to "upstream" and Server URL to "http://localhost:7005"
- Check the "Skip SSL/TLS certificate validation" option
- Start a new recording
- …

feat: Add support to start proxy with --ssl-insecure flag

---

src/main.ts
src/main/watcher.ts

This PR fixes an issue where an error shows up after restoring the main window from the dock and deleting a file from the sidebar.
- On `main` branch, close the main window on macOS using the X button
- Restore the main window from the dock
- Attempt to delete a file from the sidebar
- A runtime error shows up
- Check that the same behaviour is no longer reproducible in this branch
https://github.com/user-attachments/assets/20db9944-42f5-48b0-b61c-907dd33e4398

fix: Can't delete file after restoring window on macOS

---

src/main.ts
src/views/Recorder/Recorder.tsx

This PR addresses an issue where the user can close the main window (or quit the app) while a recording is in progress. This causes the recording to be lost as the validate and save logic isn't triggered upon exiting.
- Start a recording
- While the recording is in progress, close the main window
- Check that a prompt to stop the recording was triggered
- Check that the recording is saved after the app is closed
Resolves https://github.com/grafana/k6-studio/issues/667

feat: Prompt to save recording when closing app

---

package-lock.json
package.json
src/handlers/browser/index.ts
src/handlers/browser/launch.ts
src/main/k6StudioState.ts
src/utils/cdp/client.ts
src/utils/cdp/types.ts

This PR fixes an issue where the browser recorder extension wouldn't load if the user was using Chrome 137+. The reason is that the `--load-extension` used to load the extension has been removed for security reasons.
In both Chrome and Chromium:
1. Start a recording with browser capture enabled.
2. Make sure the in-browser UI is visible.
3. Try to generate some browser events.
4. Check that they appear in k6 Studio
5. Start another recording with browser capture disabled.
6. The in-browser UI should not be shown and no events captured.

fix(browser): Extension doesn't load when starting a recording in Chrome

---

src/components/Settings/RecorderSettings.tsx

When users install Chromium via [Flatpak](https://flatpak.org/) on Linux distros, the installation path is `/var/lib/flatpak/exports/bin/org.chromium.Chromium`, which is detected by k6 Studio as invalid.
This PR whitelists that path, so the error message is no longer displayed.
- Input `/var/lib/flatpak/exports/bin/org.chromium.Chromium` in the browser recorder path and check that error is no longer displayed
- (optionally) Install Chromium via Flatpak on a Linux distro and check that the browser launches as expected
Resolves https://github.com/grafana/k6-studio/issues/749

fix: Add support for Chromium path from Flatpak

---

src/codegen/codegen.test.ts
src/codegen/codegen.ts
src/constants/imports.ts

Closes https://github.com/grafana/k6-studio/issues/757
> [!Note]
> Add this to the release notes as it changes the output of generators that use CSV files.
> Let me know if this should have a different commit prefix
* Remove the local k6 binary in `/resources/../k6` - this is needed, because `install-k6.js` skips the installation step if a k6 binary is already present
* Run `npm i`
* Start the app
* Check that CSV data files work as expected

deps: Replace `papaparse` with `k6/experimental/csv`

---

extension/src/frontend/view/ToolBox.tsx
extension/src/frontend/view/ToolBox/ToolBoxRoot.tsx
extension/src/frontend/view/ToolBox/ToolBoxTooltip.tsx
extension/src/frontend/view/ToolBox/index.tsx
extension/src/frontend/view/settings.tsx
extension/src/frontend/view/store.ts
extension/src/frontend/view/utils.ts
package.json
src/components/primitives/Toolbar.tsx
src/components/primitives/Tooltip.tsx
vite.extension.config.mts

Closes https://github.com/grafana/k6-studio/issues/632
This PR adds the ability to re-position the in-browser toolbar. Users can drag the sidebar sideways to prevent it from covering up parts of the recorded page.
1. Start a recording
2. Re-position the toolbar by using the drag handle
3. Navigate between different pages and sites to make sure that the toolbar stays in position.
https://github.com/user-attachments/assets/344c6c1a-e2e8-4e8f-bdb4-817b52fb76d1

feat: Allow in-browser toolbar to be re-positioned

---

.github/workflows/release-test-version.yml
.github/workflows/release.yml

We are seeing the following error in CI when a PR from a fork is raised:
```
error[unpinned-uses]: unpinned action reference
--> ./.github/workflows/release-test-version.yml:27:9
|
27 |         uses: grafana/shared-workflows/actions/get-vault-secrets@get-vault-secrets-v1.2.0
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ action is not pinned to a hash (required by blanket policy)
|
= note: audit confidence → High
error[unpinned-uses]: unpinned action reference
--> ./.github/workflows/release.yml:21:9
|
21 |         uses: grafana/shared-workflows/actions/get-vault-secrets@get-vault-secrets-v1.2.0
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ action is not pinned to a hash (required by blanket policy) …
```

chore: Pin get-vault-secrets action to a hash

---

extension/src/messaging/transports/webSocketServer.ts
src/handlers/browser/launch.ts
src/handlers/browser/preload.ts
src/handlers/browser/types.ts
src/main/logger.ts
src/views/Recorder/Recorder.tsx

This PR improves the error handling when starting a recording fails because of an error with the browser recording, showing more specific error messages to the user.
- Modify `WebSocketServer.create` to throw a `WebSocketServerError` and start recording
- A new toast should be shown saying that it failed to initialize browser recording
- The recording should not start
- Modify `launchBrowser` to throw an Error inside the `try` before loading the extension
- A new toast should be shown saying that the extension couldn't load
- The recording should still start
- Modify `launchBrowser` to throw an Error before launching the browser
- The old toast should be shown
- The recording should not start

feat: Improved error handling when starting a recording

---

extension/src/background/navigation.ts

This PR fixes an issue where navigation events would be recorded for suggestions while typing in the address bar.
1. Start a recording
2. Go to various domains by typing them in the address bar
There should be no extra navigation events to e.g. google.com
Resolves https://github.com/grafana/k6-studio/issues/687

fix: Navigation events are captures while typing in address bar

---

extension/src/frontend/index.ts
extension/src/frontend/manager.ts
extension/src/frontend/view/ElementInspector/ElementMenu.utils.ts
extension/src/utils/dom.ts

This PR fixes some issues with clicking on labels:
1. If the label is associated with a checkbox/radio, both a click and check event would be recorded
2. If the label is associated with a button, two click events would be recorded (one for the label and one for the button)
This caused issues especially for checkboxes, because the duplicated events would toggle the checkbox on and off again, which is not what really happened in the browser.
1. Find a checkbox with a label (quickpizza has one, radix-ui has another)
2. Click the label
3. Check that a single click event was recorded.
Closes https://github.com/grafana/k6-studio/issues/790

fix: Clicking the label of a checkbox/radio records two events

---

src/handlers/browser/launch.ts
src/handlers/script/index.ts
src/main.ts
src/main/proxy.ts
src/main/script.ts

This PR configures k6 browser to run using the proxy recorder when validating a script. This means that users can view the browser's network traffic in order to debug issues.
1. Create a browser script.
2. Validate the script
You should the network requests that were made by the browser.

feat: Capture network traffic when running browser scripts

---

src/components/Monaco/ConstrainerCodeEditor.tsx

Fixes a bug when pasting code in custom code parameterization rule crashed the app.
1. Create a parameterization rule, select replace with -> custom code
2. Paste multi-line text into the editor
3. Verify app doesn't crash, text is pasted and function declaration is non-removable
Resolves https://github.com/grafana/k6-studio/issues/792

fix: App crashing when pasting into custom code editor

---

package-lock.json
package.json

Bump `@radix-ui/themes` to `3.2.1` to fix an issue with the dropdown menu modality, that is reproducible in Generator: when the user opens the Validator/Export dialogs from the top-right actions menu, the UI becomes inert once the dialog closes.
- Open a generator
- Click the dots menu -> Export
- Close the Export dialog
- Verify the UI is interactive

fix: UI becomes inert after interacting with dialogs opened from dropdown menu

---

src/views/Recorder/BrowserEventLog.tsx
src/views/Recorder/RecordingInspector.tsx
src/views/RecordingPreviewer/RecordingPreviewer.tsx
src/views/RecordingPreviewer/RecordingPreviewerControls.tsx

Improve discoverability of the `Export browser script` option, by lifting it to the top of the View and putting both the generator flow and the browser flow into the same `Create test` dropdown menu.
1. Open/create a recording and:
- Verify that you can create a generator
- Verify that you can export a browser script

feat(Recorder): Add create test menu to make exporting browser tests easier

---

extension/src/selectors.ts
src/codegen/browser/code/options.ts
src/codegen/browser/code/scenario.ts
src/codegen/browser/codegen.test.ts
src/codegen/browser/intermediate/ast.ts
src/codegen/browser/intermediate/index.ts
src/codegen/browser/intermediate/variables.ts
src/codegen/browser/test.ts
src/codegen/browser/types.ts
src/components/BrowserEventList/BrowserEventList.tsx
src/components/BrowserEventList/EventDescription/Selector.tsx
src/schemas/recording/v1/browser.ts

Closes https://github.com/grafana/k6-studio/issues/834
- Find a website that uses `data-testid` on its elements
- Start a recording and interact with these elements
- Verify that the testId selectors are displayed in the event log
- Verify that, when exported, the browser script uses `getByTestId`

feat(Browser): Add getByTestId support
