src/codegen/codegen.ts

fix: add back Content-Type header

---

src/codegen/codegen.ts
src/components/WebLogView/RequestDetails/Payload.tsx
src/components/WebLogView/RequestDetails/utils.ts
src/script.ts

Add support for `multipart/form-data` post requests.

feat: Handle multipart/form-data requests

---

src/views/Validator/Validator.tsx

Fixes app crash when opening validator from home page.

fix: Validator crashing when opened from home

---

package-lock.json
package.json

release v0.2.0

---

package-lock.json
package.json

release 0.2.1

---

package-lock.json
package.json

release 0.3.0

---

.github/ISSUE_TEMPLATE/bug.yaml

chore: add `needs-triage` label to new bug issues

---

src/browser.ts
src/components/Form/FieldGroup.tsx
src/components/Layout/PageHeading.tsx
src/components/Layout/Sidebar/Sidebar.tsx
src/main.ts
src/preload.ts
src/views/Recorder/EmptyState.tsx
src/views/Recorder/Recorder.tsx
src/views/Recorder/Recorder.utils.ts
src/views/RecordingPreviewer/RecordingPreviewer.tsx

1. Go to Recorder and enter a valid URL - verify that it's loaded when the browser starts
2. Go to Recorder and enter an invalid URL\some gibberish - verify that the browser starts and shows an error instead of the page

feat: URL prompt in Recorder

---

src/components/ButtonWithTooltip.tsx
src/components/Collapsible.tsx
src/components/WebLogView/Group.tsx
src/renderer.ts

chore: Wrap ButtonWithTooltip in forwardRef

---

src/usageReport.ts

This PR fixes the usage report ID that is not being properly generated upon app initialization.

fix: usage report id

---

README.md
index.html
package-lock.json
package.json
resources/splashscreen.html
src/components/ExperimentalBanner.tsx
src/components/Layout/ActivityBar/VersionLabel.tsx
src/components/Settings/UsageReportSettings.tsx
src/hooks/useSetWindowTitle.test.ts
src/hooks/useSetWindowTitle.ts
src/main.ts

Update text from `experimental` -> `public preview`.
Fixes links to documentation.

chore: public preview updates

---

src/components/Layout/ActivityBar/ActivityBar.tsx
src/components/Layout/ActivityBar/HelpButton.tsx
src/components/Layout/ActivityBar/ProxyStatusIndicator.tsx
src/components/Layout/ActivityBar/VersionLabel.tsx
src/components/Settings/RecorderSettings.tsx
src/components/WebLogView/RequestDetails/Headers.tsx
src/components/WebLogView/ResponseDetails/Headers.tsx
src/menu.ts

* New dropdown menu in the bottom left corner that groups both the documentation link and the linkt to github issues
* Documentation option in the Help menu

feat: Documentation link

---

release-please-config.json

ci: Remove bootstrap-sha from release-please config

---

src/components/WebLogView/WebLogView.tsx

fix: Type column in Request List takes too much space when window is small

---

src/components/WebLogView/ResponseDetails/Content.tsx

Apart from the scrollarea fix and padding reductions, it also fixes an issue described in the comment
Before
After

fix: Content preview layout is broken

---

.github/workflows/release.yml

ci(release): Increase heap size for publish script

---

package-lock.json

This PR fixes 2 high and 1 medium security issues as reported by `npm audit`. These only affected the development environment, but keeping them around might obscure more important issues in the future.
1. `npm i`.
2. Try to start the app.
There should be no audit warnings and the app should start like usual.

fix: Security issues reported by NPM audit

---

src/main.ts

Fixes a race condition that would prevent the splashscreen from showing.

fix: splashscreen not showing

---

src/views/Recorder/EmptyState.tsx

Updates the example URL in the generator with a new service since the one used now is getting deprecated.
If you feel that we should use a different url, please share the sentiment 🙇

fix: empty state url

---

src/codegen/codegen.test.ts
src/main.ts
src/preload.ts
src/types/har.ts
src/views/Generator/Generator.utils.ts
src/views/Generator/RecordingSelector.tsx
src/views/RecordingPreviewer/RecordingPreviewer.tsx
src/views/Validator/Validator.tsx

Verify that the following features work as expected:
* Opening recordings and generators
* Opening and running an external script

internal: Parse generator files in main

---

src/rules/parameterization.ts
src/schemas/generator/v0/rules.ts
src/schemas/generator/v1/rules.ts
src/types/rules.ts
src/views/Generator/RuleEditor/ParameterizationEditor/ValueEditor.tsx
src/views/Generator/TestRuleContainer/TestRule/TestRuleSelector.tsx

This will be replaced with DataFileValueSchema

chore: Remove ArrayValueSchema

---

src/components/Monaco/ReactMonacoEditor.tsx
src/globalStyles.ts

fix: Code editor scrollbars aren't consistent with app UI

---

src/components/Layout/ActivityBar/ActivityBar.tsx
src/components/Layout/ActivityBar/NavIconButton.tsx

Closes https://github.com/grafana/k6-studio/issues/471

fix: App logo is not clickable

---

src/schemas/generator/v1/loadZone.ts
src/views/Generator/TestOptions/LoadZones/LoadZones.tsx
src/views/Generator/TestOptions/TestOptions.tsx

This PR contains UI improvements for the Load Zones feature that need to be addressed before promoting the feature to production.
- enable the `load-zones` feature
- check the "Load zones" tab in Test Options in the Generator

internal(Load Zones): UI improvements for Load Zones feature

---

forge.config.ts
package.json

This PR reverts a name change on the executable that was introduced in the Linux support PR
N/A

fix: executable name

---

src/components/WebLogView/Row.tsx
src/components/WebLogView/SearchResults.tsx
src/components/WebLogView/WebLogView.tsx
src/views/Generator/GeneratorTabs/RequestList.tsx
src/views/Generator/GeneratorTabs/RequestRow.tsx
src/views/Generator/GeneratorTabs/RequestTable.tsx

feat: Use labels to highlight matched requests

---

resources/logo-splashscreen-dark.svg
resources/logo-splashscreen.svg
resources/splashscreen.html
src/main.ts

Comment out `splashscreenWindow.close()` in `main.ts`
https://github.com/user-attachments/assets/2cd52a9f-2115-4721-a8ac-a129e59f2d2f
https://github.com/user-attachments/assets/c0ccc347-89a9-4f1a-8291-5051407c2943

feat: Update splashscreen

---

README.md

chore: update demo video

---

.github/ISSUE_TEMPLATE/bug.yaml

Update bug template:
- Add ids to the OS and version fields
- Rename `behaviour` -> `behavior`
- Remove markdown sections
- Add an optional Bug description field

chore: Update bug template

---

package-lock.json
src/codegen/estree/traverse.ts
vite.extension.config.mts

fix(browser): Browser build failing because of missing optional dependencies

---

README.md

docs: Link contributing guide in readme

---

extension/src/frontend/view/index.tsx

This PR partially addresses https://github.com/grafana/k6-studio/issues/656. I've outlined the problem in a code comment, but I'll paste it here:
Take the following DOM:
```
<body>
<div>User element</div>
<div id="ksix-studio-mount"></div>
<div>Dynamically added later</div>
</body>
```
If the user was highlighting the dynamically added element, the selector generator could generate a selector like `body > div:nth-child(3)`. But running the generated script would always result in an error because the mount is only present when recording and the correct selector should have been `body > div:nth-child(2)`.
1. Start a recording.
2. Open devtools in the browser
3. Open Elements tab
4. Open e.g. grafana.com
5. You should see a `<div>` element be moved to the button as the page loads.
6. Try all …

internal(browser): In-browser UI breaks selector generation

---

install-k6.js

Updates k6 version to `v.0.58.0`
_Note:_ It has also been updated for the github action.

chore: update k6 version to v0.58

---

src/globalStyles.ts
src/views/RecordingPreviewer/RecordingPreviewer.tsx

fix: Cursor is inconsistent across different buttons

---

.github/workflows/ci.yml
.github/workflows/commit-lint.yml
.github/workflows/release-please.yml
.github/workflows/release-test-version.yml
.github/workflows/release.yml

Updates the actions to specify version of non `actions/` actions and sets permissions.

chore: update actions

---

.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/project_spec.md

This PR introduces two new issue templates to be used in GitHub:
- **Feature request**: a standardized format for customers or stakeholders to request new features
- **Project specification**: a standardized way of us internally creating reporting tasks that need to be worked on. (to replace the process of us manually creating blank issues)
N/A

chore: Add issue template for Feature Requests and Project Spec

---

catalog-info.yaml

This adds the file from https://github.com/grafana/k6-studio/pull/674

chore: add software catalog yaml

---

package-lock.json
package.json
src/main/__snapshots__/script/browser-options/with-browser-import.js
src/main/__snapshots__/script/browser-options/without-browser-import.js
src/main/__snapshots__/script/checks-shim/handle-summary-was-exported.js
src/main/__snapshots__/script/checks-shim/handle-summary-was-not-exported.js
src/main/__snapshots__/script/groups-shim/with-different-alias-for-execution-import.js
src/main/__snapshots__/script/groups-shim/with-http-import.js
src/main/__snapshots__/script/groups-shim/without-http-import.js
src/main/__snapshots__/script/options-export/options-export.js
src/main/__snapshots__/script/options-export/rename-complex-existing-options-export.js
src/main/__snapshots__/script/options-export/rename-existing-options-export.js
src/main/script.ts

The following script causes the validator to crash because of a stack overflow:
```ts
// Generated by Grafana k6 Studio (1.2.0) on 2025-06-10T12:42:23.684Z
import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";
export const options = {
stages: [
{ target: 20, duration: "1m" },
{ target: 20, duration: "3m30s" },
{ target: 0, duration: "1m" },
],
};
export default function () {
let params;
let resp;
let match;
let regex;
let url;
const correlation_vars = {};
group("Default group", function () {
params = {
headers: {
"upgrade-insecure-requests": `1`,
accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
"sec-fetch-site": `none`,
"sec-fetch-mode": …
```

fix: Running validator causes 'Maximum call stack size exceeded' error

---

.github/workflows/release-test-version.yml
.github/workflows/release.yml

fix: windows build

---

src/views/Recorder/RecordingInspector.tsx

fix: Browser events tab is enabled when no browser events are present
